name: Cross Compile

on:
  # Trigger when merged on main
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # Manual trigger
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:

  build:
    name: Build

    strategy:
      fail-fast: false
      matrix:
        include:
        - from: ubuntu-latest
          target: "aarch64-apple-darwin"
          features: "+aes,+neon"
        - from: ubuntu-latest
          target: "aarch64-unknown-linux-gnu"
          features: "+aes,+neon"
        - from: ubuntu-latest
          target: "aarch64-unknown-linux-musl"
          features: "+aes,+neon"
        - from: ubuntu-latest
          target: "i686-unknown-linux-gnu"
          features: "+aes,+vaes,+avx2"
        - from: ubuntu-latest
          target: "x86_64-pc-windows-msvc"
          features: "+aes,+vaes,+avx2"
        - from: ubuntu-latest
          target: "x86_64-unknown-linux-gnu"
          features: "+aes,+vaes,+avx2"
        - from: macos-latest
          target: "aarch64-apple-darwin"
          features: "+aes,+neon"
        - from: macos-latest
          target: "x86_64-unknown-linux-gnu"
          features: "+aes,+vaes,+avx2"
        # No hardware backend: software backend only
        - from: ubuntu-latest
          target: "wasm32-unknown-unknown"
        - from: ubuntu-latest
          target: "s390x-unknown-linux-gnu" # Big endian

    runs-on: ${{ matrix.from }}

    steps:
    - uses: actions/checkout@v3

    - name: Install target
      run: rustup target add ${{ matrix.target }}

    # Hardware backend detected at runtime (or software backend)
    - name: Build
      run: cargo build --release --target ${{ matrix.target }}
      env:
        RUSTFLAGS: ""

    # Hardware backend inlined
    - name: Build (target features)
      if: ${{ matrix.features }}
      run: cargo build --release --target ${{ matrix.target }}
      env:
        RUSTFLAGS: "-C target-feature=${{ matrix.features }}"
